---
title: "LAB 13 (MD)"
author: "Ingrid Villarreal V"
date: "2025-10-04"
output: html_document
---

Cargar libreria ggplot2
```{r}
library(ggplot2)
```

Leer df
```{r}
green_data <- read.csv("C:/Users/Ingrid/Desktop/Complejidad econ贸mica/LAB 13/REGESIONES FINALES.csv")
```

Echando un ojo a los datos
```{r}
names(green_data)
```

Colocando objetos
```{r}
p1 <- ggplot(data = green_data,
            mapping = aes(x = ICE_index,
                           y = GCI_index)) +
  geom_point() +
  geom_text(label = green_data$STATE,
            color = "black" ,
            size = 4) +
  geom_point() +
  geom_smooth(method = lm,
              se = FALSE,
              fullrange = T)

p1

p2 <- ggplot(data = green_data,
             mapping = aes(x = ICE_rank,
                           y = GCI_rank)) +
  geom_point() +
  geom_text(label = green_data$STATE,
            color = "black" ,
            size = 4) +
  geom_point() +
  geom_smooth(method = lm,
              se = FALSE,
              fullrange = T)

p2

p3 <- ggplot(data = green_data,
                mapping = aes(x = LPIBE,
                              y = GCI_index)) +
  geom_point() +
  geom_text(label = green_data$STATE,
            color = "black" ,
            size = 4) +
  geom_point() +
  geom_smooth(method = lm,
              se = FALSE,
              fullrange = T)

p3
```

Correl1
```{r}
require(psych)
library(psych)
library(readr)

correl <- read_csv("C:/Users/Ingrid/Desktop/Complejidad econ贸mica/LAB 13/correl.csv")
View(correl)

attach(correl)
names(correl)
pairs(correl)
pairs.panels (correl)
```

Calculamos la correlaci贸n 
```{r}
complex_corr<-cor(correl,method="pearson")
complex_corr
```

Redondeamos
```{r}
complex_corr=round(complex_corr,digits=2)
complex_corr
```

Matriz de correlaci贸n
```{r}
library(ggcorrplot)
library(ggplot2)

p4<-ggcorrplot(complex_corr,method="circle",type="lower",lab=TRUE)+ggtitle("matrizdecorrelacion")+theme_minimal()
p4

require(ggpubr)
ggpubr :: ggarrange (p1, p2, p3, p4, etiquetas = c ("A", "B", "C" , "D"))

require (gridExtra)
F1 <- grid.arrange (p1, p2, p3, p4, nrow = 2)
```

